[package]
name = "hash_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
md5 = "0.8.0"
sha1 = "0.10"
sha2 = "0.10"
sha3 = "0.10"
crc32fast = "1.5.0"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "hash_benchmark"
harness = false